// @ts-check
/**
 * Aggiorna entriesIt in items.json usando le descrizioni italiane da magic_items_with_description.json
 * Mapping: indice italiano (0-325) → id in items.json
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';

if (!existsSync('magic_items_with_description.json')) {
  console.log('[merge-italian] magic_items_with_description.json non trovato, skip.');
  process.exit(0);
}

const itItems = JSON.parse(readFileSync('magic_items_with_description.json', 'utf-8'));
const enItems = JSON.parse(readFileSync('src/data/items.json', 'utf-8'));

// Mapping: itIndex → array di item ID da aggiornare con questa descrizione italiana
// Alcuni oggetti italiani coprono più varianti inglesi (es. Dragon Scale Mail)
const MAPPING = {
  0:   ['wings-of-flying-dmg'],
  1:   ['dragon-slayer-any-sword-dmg'],
  2:   ['giant-slayer-any-sword-or-axe-dmg'],
  3:   ['iron-flask-dmg'],
  4:   ['amulet-of-proof-against-detection-and-location-dmg'],
  5:   ['amulet-of-the-planes-dmg'],
  6:   ['amulet-of-health-dmg'],
  7:   ['ring-of-spell-storing-dmg'],
  8:   ['ring-of-three-wishes-dmg'],
  9:   ['ring-of-warmth-dmg'],
  10:  ['ring-of-water-walking-dmg'],
  11:  ['ring-of-elemental-command-dmg', 'ring-of-air-elemental-command-dmg', 'ring-of-earth-elemental-command-dmg', 'ring-of-fire-elemental-command-dmg', 'ring-of-water-elemental-command-dmg'],
  12:  ['ring-of-swimming-dmg'],
  13:  ['ring-of-jumping-dmg'],
  14:  ['ring-of-the-ram-dmg'],
  15:  ['ring-of-feather-falling-dmg'],
  16:  ['ring-of-free-action-dmg'],
  17:  ['ring-of-x-ray-vision-dmg'],
  18:  ['ring-of-shooting-stars-dmg'],
  19:  ['ring-of-evasion-dmg'],
  20:  ['ring-of-djinni-summoning-dmg'],
  21:  ['ring-of-animal-influence-dmg'],
  22:  ['ring-of-invisibility-dmg'],
  23:  ['ring-of-protection-dmg'],
  24:  ['ring-of-resistance-dmg'],
  25:  ['ring-of-regeneration-dmg'],
  26:  ['ring-of-mind-shielding-dmg'],
  27:  ['ring-of-telekinesis-dmg'],
  28:  ['ring-of-spell-turning-dmg'],
  29:  ['apparatus-of-kwalish-dmg'],
  30:  ['oathbow-longbow-dmg'],
  31:  ['weapon-1-dmg'],
  32:  ['weapon-2-dmg'],
  33:  ['weapon-3-dmg'],
  34:  ['weapon-of-warning-dmg'],
  35:  ['vicious-weapon-any-weapon-dmg'],
  36:  ['armor-1-dmg'],
  37:  ['armor-2-dmg'],
  38:  ['armor-3-dmg'],
  39:  ['adamantine-armor-dmg'],
  40:  ['plate-armor-of-etherealness-dmg'],
  41:  ['dwarven-plate-dmg'],
  42:  ['mariner-s-armor-dmg'],
  43:  ['armor-of-invulnerability-dmg'],
  44:  ['armor-of-resistance-dmg'],
  45:  ['armor-of-vulnerability-bludgeoning-dmg', 'armor-of-vulnerability-piercing-dmg', 'armor-of-vulnerability-slashing-dmg'],
  46:  ['demon-armor-plate-cursed-dmg'],
  47:  ['glamoured-studded-leather-dmg'],
  48:  ['mithral-armor-medium-or-heavy-not-hide-dmg'],
  49:  ['axe-of-the-dwarvish-lords-dmg'],  // Ascia del Berserker → Berserker Axe (non presente, uso questo)
  50:  ['wand-of-magic-missiles-dmg'],
  51:  ['wand-of-lightning-bolts-dmg'],
  52:  ['wand-of-secrets-dmg'],
  53:  ['wand-of-binding-dmg'],
  54:  ['wand-of-the-war-mage-1-dmg', '1-wand-of-the-war-mage-dmg'],
  55:  ['wand-of-the-war-mage-2-dmg', '2-wand-of-the-war-mage-dmg'],
  56:  ['wand-of-the-war-mage-3-dmg', '3-wand-of-the-war-mage-dmg'],
  57:  ['wand-of-polymorph-dmg'],
  58:  ['wand-of-paralysis-dmg'],
  59:  ['wand-of-fear-dmg'],
  60:  ['wand-of-web-dmg'],
  61:  ['wand-of-wonder-dmg'],
  62:  ['wand-of-fireballs-dmg'],
  63:  ['wand-of-enemy-detection-dmg'],
  64:  ['wand-of-magic-detection-dmg'],
  65:  ['folding-boat-dmg'],
  66:  ['staff-of-the-woodlands-dmg'],
  67:  ['staff-of-the-magi-dmg'],
  68:  ['staff-of-thunder-and-lightning-dmg'],
  69:  ['staff-of-striking-dmg'],
  70:  ['staff-of-withering-dmg'],
  71:  ['staff-of-fire-dmg'],
  72:  ['staff-of-frost-dmg'],
  73:  ['staff-of-the-python-dmg'],
  74:  ['staff-of-power-dmg'],
  75:  ['staff-of-healing-dmg'],
  76:  ['staff-of-the-adder-dmg'],
  77:  ['staff-of-charming-dmg'],
  78:  ['staff-of-swarming-insects-dmg'],
  79:  ['bead-of-force-dmg'],
  80:  ['bowl-of-commanding-water-elementals-dmg'],
  81:  ['bag-of-holding-dmg'],
  82:  ['bag-of-beans-dmg'],
  83:  ['bag-of-tricks-dmg', 'bag-of-tricks-gray-dmg', 'bag-of-tricks-rust-dmg', 'bag-of-tricks-tan-dmg'],
  84:  ['bag-of-devouring-dmg'],
  85:  ['eversmoking-bottle-dmg'],
  86:  ['efreeti-bottle-dmg'],
  87:  ['bracers-of-archery-dmg'],
  88:  ['bracers-of-defense-dmg'],
  89:  ['brazier-of-commanding-fire-elementals-dmg'],
  90:  ['portable-hole-dmg'],
  91:  ['chime-of-opening-dmg'],
  92:  ['candle-of-invocation-dmg'],
  93:  ['cape-of-the-mountebank-dmg'],
  94:  ['hat-of-disguise-dmg'],
  95:  ['decanter-of-endless-water-dmg'],
  96:  ['belt-of-giant-strength-hill-dmg', 'belt-of-hill-giant-strength-dmg'],
  97:  ['belt-of-giant-strength-stone-frost-dmg', 'belt-of-frost-giant-strength-dmg', 'belt-of-stone-giant-strength-dmg'],
  98:  ['belt-of-giant-strength-fire-dmg', 'belt-of-fire-giant-strength-dmg'],
  99:  ['belt-of-giant-strength-cloud-dmg', 'belt-of-cloud-giant-strength-dmg'],
  100: ['belt-of-giant-strength-storm-dmg', 'belt-of-storm-giant-strength-dmg'],
  101: ['belt-of-dwarvenkind-dmg'],
  102: ['sovereign-glue-dmg'],
  103: ['necklace-of-prayer-beads-blessing-dmg', 'necklace-of-prayer-beads-curing-dmg', 'necklace-of-prayer-beads-favor-dmg', 'necklace-of-prayer-beads-smiting-dmg', 'necklace-of-prayer-beads-summons-dmg', 'necklace-of-prayer-beads-wind-walking-dmg'],
  104: ['necklace-of-adaptation-dmg'],
  105: ['necklace-of-fireballs-1-bead-dmg', 'necklace-of-fireballs-2-beads-dmg', 'necklace-of-fireballs-3-beads-dmg', 'necklace-of-fireballs-4-beads-dmg', 'necklace-of-fireballs-5-beads-dmg', 'necklace-of-fireballs-6-beads-dmg'],
  106: ['cap-of-water-breathing-dmg'],
  107: ['dragon-scale-mail-dmg', 'black-dragon-scale-mail-dmg', 'blue-dragon-scale-mail-dmg', 'brass-dragon-scale-mail-dmg', 'bronze-dragon-scale-mail-dmg', 'copper-dragon-scale-mail-dmg', 'gold-dragon-scale-mail-dmg', 'green-dragon-scale-mail-dmg', 'red-dragon-scale-mail-dmg', 'silver-dragon-scale-mail-dmg', 'white-dragon-scale-mail-dmg'],
  108: ['rope-of-entanglement-dmg'],
  109: ['rope-of-climbing-dmg'],
  110: ['horn-of-valhalla-brass-dmg'],
  111: ['horn-of-valhalla-silver-dmg'],
  112: ['horn-of-valhalla-bronze-dmg'],
  113: ['horn-of-valhalla-iron-dmg'],
  114: ['horn-of-blasting-dmg'],
  115: ['efreeti-chain-chain-mail-dmg'],
  116: ['cubic-gate-dmg'],
  117: ['cube-of-force-dmg'],
  118: ['circlet-of-blasting-dmg'],
  119: ['defender-any-sword-dmg'],
  120: ['elixir-of-health-dmg'],
  121: ['helm-of-teleportation-dmg'],
  122: ['helm-of-comprehending-languages-dmg'],
  123: ['helm-of-brilliance-dmg'],
  124: ['helm-of-telepathy-dmg'],
  125: ['quiver-of-ehlonna-dmg'],
  126: ['iron-bands-of-bilarro-dmg'],
  127: ['headband-of-intellect-dmg'],
  128: ['brooch-of-shielding-dmg'],
  129: ['horseshoes-of-speed-dmg'],
  130: ['horseshoes-of-a-zephyr-dmg'],
  131: ['philter-of-love-dmg'],
  132: ['pipes-of-the-sewers-dmg'],
  133: ['pipes-of-haunting-dmg'],
  134: ['daern-s-instant-fortress-dmg'],
  135: ['arrow-of-slaying-ea-dmg'],
  136: ['gem-of-brightness-dmg'],
  137: ['gem-of-seeing-dmg'],
  138: ['elemental-gem-dmg', 'elemental-gem-blue-sapphire-dmg', 'elemental-gem-emerald-dmg', 'elemental-gem-red-corundum-dmg', 'elemental-gem-yellow-diamond-dmg'],
  139: ['elven-chain-dmg'],
  140: ['alchemy-jug-dmg'],
  141: ['javelin-of-lightning-dmg'],
  142: ['driftglobe-dmg'],
  143: ['gloves-of-missile-snaring-dmg'],
  144: ['gloves-of-swimming-and-climbing-dmg'],
  145: ['gauntlets-of-ogre-power-dmg'],
  146: ['gloves-of-thievery-dmg'],
  147: ['censer-of-controlling-air-elementals-dmg'],
  148: ['sun-blade-longsword-dmg'],
  // 149: Lama della Fortuna = Luck Blade — non trovata in items.json DMG, saltata
  150: ['lantern-of-revealing-dmg'],
  151: ['eyes-of-the-eagle-dmg'],
  152: ['eyes-of-minute-seeing-dmg'],
  153: ['eyes-of-charming-dmg'],
  154: ['flame-tongue-dmg'],
  155: ['dimensional-shackles-dmg'],
  156: ['cloak-of-the-bat-dmg'],
  157: ['cloak-of-arachnida-dmg'],
  158: ['cloak-of-invisibility-dmg'],
  159: ['cloak-of-the-manta-ray-dmg'],
  160: ['cloak-of-protection-dmg'],
  161: ['cloak-of-displacement-dmg'],
  162: ['cloak-of-elvenkind-dmg'],
  163: ['mantle-of-spell-resistance-dmg'],
  164: ['manual-of-golems-dmg', 'manual-of-clay-golems-dmg', 'manual-of-flesh-golems-dmg', 'manual-of-iron-golems-dmg', 'manual-of-stone-golems-dmg'],
  165: ['manual-of-gainful-exercise-dmg'],
  166: ['manual-of-bodily-health-dmg'],
  167: ['manual-of-quickness-of-action-dmg'],
  168: ['hammer-of-thunderbolts-maul-dmg'],
  169: ['dwarven-thrower-warhammer-dmg'],
  170: ['mace-of-terror-dmg'],
  171: ['mace-of-smiting-dmg'],
  172: ['mace-of-disruption-dmg'],
  173: ['deck-of-illusions-dmg'],
  174: ['deck-of-many-things-dmg'],
  175: ['medallion-of-thoughts-dmg'],
  176: ['ammunition-1-ea-dmg'],
  177: ['ammunition-2-ea-dmg'],
  178: ['ammunition-3-ea-dmg'],
  179: ['goggles-of-night-dmg'],
  180: ['oil-of-sharpness-dmg'],
  181: ['oil-of-etherealness-dmg'],
  182: ['oil-of-slipperiness-dmg'],
  183: ['slippers-of-spider-climbing-dmg'],
  184: ['scroll-of-protection-dmg', 'scroll-of-protection-from-aberrations-dmg', 'scroll-of-protection-from-beasts-dmg', 'scroll-of-protection-from-celestials-dmg', 'scroll-of-protection-from-elementals-dmg', 'scroll-of-protection-from-fey-dmg', 'scroll-of-protection-from-fiends-dmg', 'scroll-of-protection-from-plants-dmg', 'scroll-of-protection-from-undead-dmg'],
  185: ['spell-scroll-level-0-dmg'],
  186: ['spell-scroll-level-1-dmg'],
  187: ['spell-scroll-level-2-dmg'],
  188: ['spell-scroll-level-3-dmg'],
  189: ['spell-scroll-level-4-dmg'],
  190: ['spell-scroll-level-5-dmg'],
  191: ['spell-scroll-level-6-dmg'],
  192: ['spell-scroll-level-7-dmg'],
  193: ['spell-scroll-level-8-dmg'],
  194: ['spell-scroll-level-9-dmg'],
  195: ['pearl-of-power-dmg'],
  196: ['stone-of-controlling-earth-elementals-dmg'],
  197: ['stone-of-good-luck-luckstone-dmg'],
  198: ['ioun-stone-awareness-dmg'],
  199: ['ioun-stone-protection-dmg'],
  200: ['ioun-stone-reserve-dmg'],
  201: ['ioun-stone-sustenance-dmg'],
  202: ['ioun-stone-agility-dmg'],
  203: ['ioun-stone-absorption-dmg'],
  204: ['ioun-stone-leadership-dmg'],
  205: ['ioun-stone-strength-dmg'],
  206: ['ioun-stone-intellect-dmg'],
  207: ['ioun-stone-insight-dmg'],
  208: ['ioun-stone-fortitude-dmg'],
  209: ['ioun-stone-greater-absorption-dmg'],
  210: ['ioun-stone-mastery-dmg'],
  211: ['ioun-stone-regeneration-dmg'],
  212: ['sending-stones-dmg'],
  213: ['nolzur-s-marvelous-pigments-dmg'],
  214: ['quaals-feather-token-anchor-dmg', 'quaals-feather-token-bird-dmg', 'quaals-feather-token-fan-dmg', 'quaals-feather-token-swan-boat-dmg', 'quaals-feather-token-whip-dmg', 'quaal-s-feather-token-tree-dmg'],
  215: ['dust-of-disappearance-dmg'],
  216: ['dust-of-sneezing-and-choking-dmg'],
  217: ['dust-of-dryness-1-pellet-dmg'],
  218: ['potion-of-water-breathing-dmg'],
  219: ['potion-of-fire-breath-dmg'],
  220: ['potion-of-gaseous-form-dmg'],
  221: ['potion-of-giant-strength-hill-dmg', 'potion-of-hill-giant-strength-dmg'],
  222: ['potion-of-giant-strength-frost-stone-dmg', 'potion-of-frost-giant-strength-dmg', 'potion-of-stone-giant-strength-dmg'],
  223: ['potion-of-giant-strength-fire-dmg', 'potion-of-fire-giant-strength-dmg'],
  224: ['potion-of-giant-strength-cloud-dmg', 'potion-of-cloud-giant-strength-dmg'],
  225: ['potion-of-giant-strength-storm-dmg', 'potion-of-storm-giant-strength-dmg'],
  226: ['potion-of-animal-friendship-dmg'],
  227: ['potion-of-clairvoyance-dmg'],
  228: ['potion-of-growth-dmg'],
  229: ['potion-of-diminution-dmg'],
  230: ['potion-of-heroism-dmg'],
  231: ['potion-of-healing-dmg'],
  232: ['potion-of-healing-greater-dmg', 'potion-of-greater-healing-dmg'],
  233: ['potion-of-healing-superior-dmg', 'potion-of-superior-healing-dmg'],
  234: ['potion-of-healing-supreme-dmg', 'potion-of-supreme-healing-dmg'],
  235: ['potion-of-invisibility-dmg'],
  236: ['potion-of-invulnerability-dmg'],
  237: ['potion-of-mind-reading-dmg'],
  238: ['potion-of-longevity-dmg'],
  239: ['potion-of-resistance-dmg'],
  240: ['potion-of-climbing-dmg'],
  241: ['potion-of-speed-dmg'],
  242: ['potion-of-vitality-dmg'],
  243: ['potion-of-flying-dmg'],
  244: ['potion-of-poison-dmg'],
  245: ['well-of-many-worlds-dmg'],
  246: ['dagger-of-venom-dmg'],
  247: ['holy-avenger-any-sword-dmg'],
  248: ['scarab-of-protection-dmg'],
  249: ['scimitar-of-speed-dmg'],
  250: ['broom-of-flying-dmg'],
  251: ['shield-1-dmg'],
  252: ['shield-2-dmg'],
  253: ['shield-3-dmg'],
  254: ['animated-shield-dmg'],
  255: ['spellguard-shield-dmg'],
  256: ['shield-of-missile-attraction-dmg'],
  257: ['arrow-catching-shield-dmg'],
  258: ['sentinel-shield-dmg'],
  259: ['saddle-of-the-cavalier-dmg'],
  260: ['sphere-of-annihilation-dmg'],
  261: ['crystal-ball-dmg', 'crystal-ball-of-mind-reading-dmg', 'crystal-ball-of-telepathy-dmg', 'crystal-ball-of-true-seeing-dmg'],
  262: ['universal-solvent-dmg'],
  263: ['sword-of-sharpness-slashing-swords-dmg'],
  264: ['dancing-sword-any-sword-dmg'],
  265: ['sword-of-wounding-any-sword-dmg'],
  266: ['sword-of-life-stealing-any-sword-dmg'],
  267: ['sword-of-vengeance-any-sword-dmg'],
  268: ['sword-of-answering-dmg', 'sword-of-answering-answerer-dmg', 'sword-of-answering-back-talker-dmg', 'sword-of-answering-concluder-dmg', 'sword-of-answering-last-quip-dmg', 'sword-of-answering-rebutter-dmg', 'sword-of-answering-replier-dmg', 'sword-of-answering-retorter-dmg', 'sword-of-answering-scather-dmg', 'sword-of-answering-squelcher-dmg'],
  269: ['nine-lives-stealer-fully-charged-any-sword-dmg'],
  270: ['vorpal-sword-dmg'],
  271: ['frost-brand-any-sword-dmg'],
  272: ['mirror-of-life-trapping-dmg'],
  273: ['figurine-of-wondrous-power-onyx-dog-dmg'],
  274: ['figurine-of-wondrous-power-ivory-goats-dmg', 'figurine-of-wondrous-power-ivory-goats-terror-dmg', 'figurine-of-wondrous-power-ivory-goats-travail-dmg', 'figurine-of-wondrous-power-ivory-goats-travelling-dmg'],
  275: ['figurine-of-wondrous-power-silver-raven-dmg'],
  276: ['figurine-of-wondrous-power-marble-elephant-dmg'],
  277: ['figurine-of-wondrous-power-bronze-griffon-dmg'],
  278: ['figurine-of-wondrous-power-serpentine-owl-dmg'],
  279: ['figurine-of-wondrous-power-golden-lions-dmg'],
  280: ['figurine-of-wondrous-power-ebony-fly-dmg'],
  281: ['figurine-of-wondrous-power-obsidian-steed-dmg'],
  282: ['winged-boots-dmg'],
  283: ['boots-of-the-winterlands-dmg'],
  284: ['boots-of-levitation-dmg'],
  285: ['boots-of-speed-dmg'],
  286: ['boots-of-elvenkind-dmg'],
  287: ['boots-of-striding-and-springing-dmg'],
  288: ['instrument-of-the-bards-anstruth-harp-dmg'],
  289: ['instrument-of-the-bards-ollamh-harp-dmg'],
  290: ['instrument-of-the-bards-fochlucan-bandore-dmg', 'instrument-of-the-bards-fochulan-bandore-dmg'],
  291: ['instrument-of-the-bards-mac-fuirmidh-cittern-dmg'],
  292: ['instrument-of-the-bards-cli-lyre-dmg'],
  293: ['instrument-of-the-bards-doss-lute-dmg'],
  294: ['instrument-of-the-bards-canaith-mandolin-dmg'],
  295: ['periapt-of-proof-against-poison-dmg'],
  296: ['talisman-of-pure-good-dmg'],
  297: ['talisman-of-ultimate-evil-dmg'],
  298: ['periapt-of-wound-closure-dmg'],
  299: ['periapt-of-health-dmg'],
  300: ['talisman-of-the-sphere-dmg'],
  301: ['carpet-of-flying-dmg', 'carpet-of-flying-3-ft-5-ft-dmg', 'carpet-of-flying-4-ft-6-ft-dmg', 'carpet-of-flying-5-ft-7-ft-dmg', 'carpet-of-flying-6-ft-9-ft-dmg'],
  302: ['tome-of-leadership-and-influence-dmg'],
  303: ['tome-of-clear-thought-dmg'],
  304: ['tome-of-understanding-dmg'],
  305: ['tome-of-the-stilled-tongue-dmg'],
  306: ['trident-of-fish-command-dmg'],
  307: ['robe-of-eyes-dmg'],
  308: ['robe-of-useful-items-dmg'],
  309: ['robe-of-scintillating-colors-dmg'],
  310: ['robe-of-the-archmagi-dmg'],
  311: ['robe-of-stars-dmg'],
  312: ['keoghtom-s-ointment-per-dose-dmg'],
  313: ['wind-fan-dmg'],
  314: ['tentacle-rod-dmg'],
  315: ['rod-of-the-pact-keeper-1-dmg', '1-rod-of-the-pact-keeper-dmg'],
  316: ['rod-of-the-pact-keeper-2-dmg', '2-rod-of-the-pact-keeper-dmg'],
  317: ['rod-of-the-pact-keeper-3-dmg', '3-rod-of-the-pact-keeper-dmg'],
  318: ['rod-of-alertness-dmg'],
  319: ['rod-of-absorption-dmg'],
  320: ['rod-of-lordly-might-dmg'],
  321: ['rod-of-resurrection-dmg'],
  322: ['rod-of-security-dmg'],
  323: ['rod-of-rulership-dmg'],
  324: ['immovable-rod-dmg'],
  325: ['heward-s-handy-haversack-dmg', 'handy-haversack-dmg'],
};

// Build lookup map: id → index in enItems
const idToIdx = {};
enItems.forEach((item, idx) => { idToIdx[item.id] = idx; });

let updated = 0;
let notFound = 0;
const skipped = []; // IT indici senza mapping

for (const [itIdxStr, ids] of Object.entries(MAPPING)) {
  const itIdx = Number(itIdxStr);
  const itItem = itItems[itIdx];
  const itDescription = itItem.description;

  for (const id of ids) {
    const enIdx = idToIdx[id];
    if (enIdx === undefined) {
      console.warn(`⚠️  ID non trovato: ${id} (da "${itItem.name}")`);
      notFound++;
      continue;
    }
    enItems[enIdx].entriesIt = itDescription;
    updated++;
  }
}

// Oggetti IT non mappati
for (let i = 0; i < itItems.length; i++) {
  if (!(i in MAPPING)) skipped.push(`[${i}] ${itItems[i].name}`);
}

writeFileSync('src/data/items.json', JSON.stringify(enItems, null, 2), 'utf-8');

console.log(`\n✅ Aggiornati: ${updated} oggetti EN`);
console.log(`⚠️  ID non trovati: ${notFound}`);
if (skipped.length) {
  console.log(`\nOggetti IT saltati (senza mapping):`);
  skipped.forEach(s => console.log(' -', s));
}
